name: apptimize_flutter
description: Apptimize Library for AB testing Flutter applications.
version: 1.0.0
homepage: https://www.apptimize.com
repository: https://github.com/urbanairship/apptimize-flutter/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.apptimize.apptimize_flutter
        pluginClass: ApptimizeFlutterPlugin
      ios:
        pluginClass: ApptimizeFlutterPlugin
